In [1]:
import os
from tqdm import tqdm
# import feather
import pandas as pd
import numpy as np
from scipy import stats
import gc
from joblib import Parallel, delayed
from math import sqrt

In [3]:
import os
x = {i for i in range(20)}
os.sched_setaffinity(0, x)

AttributeError: module 'os' has no attribute 'sched_setaffinity'

In [6]:
Parallel(n_jobs=20)(delayed(sqrt)(i ** 2) for i in range(10000000))

Process ForkPoolWorker-23:
Process ForkPoolWorker-31:
Process ForkPoolWorker-40:
Process ForkPoolWorker-35:
Process ForkPoolWorker-32:
Process ForkPoolWorker-34:
Process ForkPoolWorker-29:
Process ForkPoolWorker-22:
Process ForkPoolWorker-37:
Process ForkPoolWorker-36:
Process ForkPoolWorker-39:
Process ForkPoolWorker-38:
Process ForkPoolWorker-24:
Process ForkPoolWorker-25:
Process ForkPoolWorker-33:
Process ForkPoolWorker-27:
Process ForkPoolWorker-30:
Process ForkPoolWorker-26:
Process ForkPoolWorker-28:
Process ForkPoolWorker-21:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
Traceback (most recent call last):
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
KeyboardInterrupt
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 384, in put
    wlock_acquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
KeyboardInterrupt
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 386, in put
    return send(obj)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/site-packages/joblib/pool.py", line 372, in send
    self._writer.send_bytes(buffer.getvalue())
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/watts/anaconda3/envs/rss/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
KeyboardInterrupt

KeyboardInterrupt:

In [1]:
dates = ['2015-01-01',
 '2015-01-02',
 '2015-01-03',
 '2015-01-04',
 '2015-01-05',
 '2015-01-06',
 '2015-01-07',
 '2015-01-08',
 '2015-01-09',
 '2015-01-10',
 '2015-01-11',
 '2015-01-12',
 '2015-01-13',
 '2015-01-14',
 '2015-01-15',
 '2015-01-16',
 '2015-01-17',
 '2015-01-18',
 '2015-01-19',
 '2015-01-20',
 '2015-01-21',
 '2015-01-22',
 '2015-01-23',
 '2015-01-24',
 '2015-01-25',
 '2015-01-26',
 '2015-01-27',
 '2015-01-28',
 '2015-01-29',
 '2015-01-30',
 '2015-01-31',
 '2015-02-01',
 '2015-02-02',
 '2015-02-03',
 '2015-02-04',
 '2015-02-05',
 '2015-02-06',
 '2015-02-07',
 '2015-02-08',
 '2015-02-09',
 '2015-02-10',
 '2015-02-11',
 '2015-02-12',
 '2015-02-13',
 '2015-02-14',
 '2015-02-15',
 '2015-02-16',
 '2015-02-17',
 '2015-02-18',
 '2015-02-19',
 '2015-02-20',
 '2015-02-21',
 '2015-02-22',
 '2015-02-23',
 '2015-02-24',
 '2015-02-25',
 '2015-02-26',
 '2015-02-27',
 '2015-02-28',
 '2015-03-01',
 '2015-03-02',
 '2015-03-03',
 '2015-03-04',
 '2015-03-05',
 '2015-03-06',
 '2015-03-07',
 '2015-03-08',
 '2015-03-09',
 '2015-03-10',
 '2015-03-11',
 '2015-03-12',
 '2015-03-13',
 '2015-03-14',
 '2015-03-15',
 '2015-03-16',
 '2015-03-17',
 '2015-03-18',
 '2015-03-19',
 '2015-03-20',
 '2015-03-21',
 '2015-03-22',
 '2015-03-23',
 '2015-03-24',
 '2015-03-25',
 '2015-03-26',
 '2015-03-27',
 '2015-03-28',
 '2015-03-29',
 '2015-03-30',
 '2015-03-31',
 '2015-04-01',
 '2015-04-02',
 '2015-04-03',
 '2015-04-04',
 '2015-04-05',
 '2015-04-06',
 '2015-04-07',
 '2015-04-08',
 '2015-04-09',
 '2015-04-10',
 '2015-04-11',
 '2015-04-12',
 '2015-04-13',
 '2015-04-14',
 '2015-04-15',
 '2015-04-16',
 '2015-04-17',
 '2015-04-18',
 '2015-04-19',
 '2015-04-20',
 '2015-04-21',
 '2015-04-22',
 '2015-04-23',
 '2015-04-24',
 '2015-04-25',
 '2015-04-26',
 '2015-04-27',
 '2015-04-28',
 '2015-04-29',
 '2015-04-30',
 '2015-05-01',
 '2015-05-02',
 '2015-05-03',
 '2015-05-04',
 '2015-05-05',
 '2015-05-06',
 '2015-05-07',
 '2015-05-08',
 '2015-05-09',
 '2015-05-10',
 '2015-05-11',
 '2015-05-12',
 '2015-05-13',
 '2015-05-14',
 '2015-05-15',
 '2015-05-16',
 '2015-05-17',
 '2015-05-18',
 '2015-05-19',
 '2015-05-20',
 '2015-05-21',
 '2015-05-22',
 '2015-05-23',
 '2015-05-24',
 '2015-05-25',
 '2015-05-26',
 '2015-05-27',
 '2015-05-28',
 '2015-05-29',
 '2015-05-30',
 '2015-05-31',
 '2015-06-01',
 '2015-06-02',
 '2015-06-03',
 '2015-06-04',
 '2015-06-05',
 '2015-06-06',
 '2015-06-07',
 '2015-06-08',
 '2015-06-09',
 '2015-06-10',
 '2015-06-11',
 '2015-06-12',
 '2015-06-13',
 '2015-06-14',
 '2015-06-15',
 '2015-06-16',
 '2015-06-17',
 '2015-06-18',
 '2015-06-19',
 '2015-06-20',
 '2015-06-21',
 '2015-06-22',
 '2015-06-23',
 '2015-06-24',
 '2015-06-25',
 '2015-06-26',
 '2015-06-27',
 '2015-06-28',
 '2015-06-29',
 '2015-06-30',
 '2015-07-01',
 '2015-07-02',
 '2015-07-03',
 '2015-07-04',
 '2015-07-05',
 '2015-07-06',
 '2015-07-07',
 '2015-07-08',
 '2015-07-09',
 '2015-07-10',
 '2015-07-11',
 '2015-07-12',
 '2015-07-13',
 '2015-07-14',
 '2015-07-15',
 '2015-07-16',
 '2015-07-17',
 '2015-07-18',
 '2015-07-19',
 '2015-07-20',
 '2015-07-21',
 '2015-07-22',
 '2015-07-23',
 '2015-07-24',
 '2015-07-25',
 '2015-07-26',
 '2015-07-27',
 '2015-07-28',
 '2015-07-29',
 '2015-07-30',
 '2015-07-31',
 '2015-08-01',
 '2015-08-02',
 '2015-08-03',
 '2015-08-04',
 '2015-08-05',
 '2015-08-06',
 '2015-08-07',
 '2015-08-08',
 '2015-08-09',
 '2015-08-10',
 '2015-08-11',
 '2015-08-12',
 '2015-08-13',
 '2015-08-14',
 '2015-08-15',
 '2015-08-16',
 '2015-08-17',
 '2015-08-18',
 '2015-08-19',
 '2015-08-20',
 '2015-08-21',
 '2015-08-22',
 '2015-08-23',
 '2015-08-24',
 '2015-08-25',
 '2015-08-26',
 '2015-08-27',
 '2015-08-28',
 '2015-08-29',
 '2015-08-30',
 '2015-08-31',
 '2015-09-01',
 '2015-09-02',
 '2015-09-03',
 '2015-09-04',
 '2015-09-05',
 '2015-09-06',
 '2015-09-07',
 '2015-09-08',
 '2015-09-09',
 '2015-09-10',
 '2015-09-11',
 '2015-09-12',
 '2015-09-13',
 '2015-09-14',
 '2015-09-15',
 '2015-09-16',
 '2015-09-17',
 '2015-09-18',
 '2015-09-19',
 '2015-09-20',
 '2015-09-21',
 '2015-09-22',
 '2015-09-23',
 '2015-09-24',
 '2015-09-25',
 '2015-09-26',
 '2015-09-27',
 '2015-09-28',
 '2015-09-29',
 '2015-09-30',
 '2015-10-01',
 '2015-10-02',
 '2015-10-03',
 '2015-10-04',
 '2015-10-05',
 '2015-10-06',
 '2015-10-07',
 '2015-10-08',
 '2015-10-09',
 '2015-10-10',
 '2015-10-11',
 '2015-10-12',
 '2015-10-13',
 '2015-10-14',
 '2015-10-15',
 '2015-10-16',
 '2015-10-17',
 '2015-10-18',
 '2015-10-19',
 '2015-10-20',
 '2015-10-21',
 '2015-10-22',
 '2015-10-23',
 '2015-10-24',
 '2015-10-25',
 '2015-10-26',
 '2015-10-27',
 '2015-10-28',
 '2015-10-29',
 '2015-10-30',
 '2015-10-31',
 '2015-11-01',
 '2015-11-02',
 '2015-11-03',
 '2015-11-04',
 '2015-11-05',
 '2015-11-06',
 '2015-11-07',
 '2015-11-08',
 '2015-11-09',
 '2015-11-10',
 '2015-11-11',
 '2015-11-12',
 '2015-11-13',
 '2015-11-14',
 '2015-11-15',
 '2015-11-16',
 '2015-11-17',
 '2015-11-18',
 '2015-11-19',
 '2015-11-20',
 '2015-11-21',
 '2015-11-22',
 '2015-11-23',
 '2015-11-24',
 '2015-11-25',
 '2015-11-26',
 '2015-11-27',
 '2015-11-28',
 '2015-11-29',
 '2015-11-30',
 '2015-12-01',
 '2015-12-02',
 '2015-12-03',
 '2015-12-04',
 '2015-12-05',
 '2015-12-06',
 '2015-12-07',
 '2015-12-08',
 '2015-12-09',
 '2015-12-10',
 '2015-12-11',
 '2015-12-12',
 '2015-12-13',
 '2015-12-14',
 '2015-12-15',
 '2015-12-16',
 '2015-12-17',
 '2015-12-18',
 '2015-12-19',
 '2015-12-20',
 '2015-12-21',
 '2015-12-22',
 '2015-12-23',
 '2015-12-24',
 '2015-12-25',
 '2015-12-26',
 '2015-12-27',
 '2015-12-28',
 '2015-12-29',
 '2015-12-30',
 '2015-12-31',
 '2016-01-01',
 '2016-01-02',
 '2016-01-03',
 '2016-01-04',
 '2016-01-05',
 '2016-01-06',
 '2016-01-07',
 '2016-01-08',
 '2016-01-09',
 '2016-01-10',
 '2016-01-11',
 '2016-01-12',
 '2016-01-13',
 '2016-01-14',
 '2016-01-15',
 '2016-01-16',
 '2016-01-17',
 '2016-01-18',
 '2016-01-19',
 '2016-01-20',
 '2016-01-21',
 '2016-01-22',
 '2016-01-23',
 '2016-01-24',
 '2016-01-25',
 '2016-01-26',
 '2016-01-27',
 '2016-01-28',
 '2016-01-29',
 '2016-01-30',
 '2016-01-31',
 '2016-02-01',
 '2016-02-02',
 '2016-02-03',
 '2016-02-04',
 '2016-02-05',
 '2016-02-06',
 '2016-02-07',
 '2016-02-08',
 '2016-02-09',
 '2016-02-10',
 '2016-02-11',
 '2016-02-12',
 '2016-02-13',
 '2016-02-14',
 '2016-02-15',
 '2016-02-16',
 '2016-02-17',
 '2016-02-18',
 '2016-02-19',
 '2016-02-20',
 '2016-02-21',
 '2016-02-22',
 '2016-02-23',
 '2016-02-24',
 '2016-02-25',
 '2016-02-26',
 '2016-02-27',
 '2016-02-28',
 '2016-02-29',
 '2016-03-01',
 '2016-03-02',
 '2016-03-03',
 '2016-03-04',
 '2016-03-05',
 '2016-03-06',
 '2016-03-07',
 '2016-03-08',
 '2016-03-09',
 '2016-03-10',
 '2016-03-11',
 '2016-03-12',
 '2016-03-13',
 '2016-03-14',
 '2016-03-15',
 '2016-03-16',
 '2016-03-17',
 '2016-03-18',
 '2016-03-19',
 '2016-03-20',
 '2016-03-21',
 '2016-03-22',
 '2016-03-23',
 '2016-03-24',
 '2016-03-25',
 '2016-03-26',
 '2016-03-27',
 '2016-03-28',
 '2016-03-29',
 '2016-03-30',
 '2016-03-31',
 '2016-04-01',
 '2016-04-02',
 '2016-04-03',
 '2016-04-04',
 '2016-04-05',
 '2016-04-06',
 '2016-04-07',
 '2016-04-08',
 '2016-04-09',
 '2016-04-10',
 '2016-04-11',
 '2016-04-12',
 '2016-04-13',
 '2016-04-14',
 '2016-04-15',
 '2016-04-16',
 '2016-04-17',
 '2016-04-18',
 '2016-04-19',
 '2016-04-20',
 '2016-04-21',
 '2016-04-22',
 '2016-04-23',
 '2016-04-24',
 '2016-04-25',
 '2016-04-26',
 '2016-04-27',
 '2016-04-28',
 '2016-04-29',
 '2016-04-30',
 '2016-05-01',
 '2016-05-02',
 '2016-05-03',
 '2016-05-04',
 '2016-05-05',
 '2016-05-06',
 '2016-05-07',
 '2016-05-08',
 '2016-05-09',
 '2016-05-10',
 '2016-05-11',
 '2016-05-12',
 '2016-05-13',
 '2016-05-14',
 '2016-05-15',
 '2016-05-16',
 '2016-05-17',
 '2016-05-18',
 '2016-05-19',
 '2016-05-20',
 '2016-05-21',
 '2016-05-22',
 '2016-05-23',
 '2016-05-24',
 '2016-05-25',
 '2016-05-26',
 '2016-05-27',
 '2016-05-28',
 '2016-05-29',
 '2016-05-30',
 '2016-05-31',
 '2016-06-01',
 '2016-06-02',
 '2016-06-03',
 '2016-06-04',
 '2016-06-05',
 '2016-06-06',
 '2016-06-07',
 '2016-06-08',
 '2016-06-09',
 '2016-06-10',
 '2016-06-11',
 '2016-06-12',
 '2016-06-13',
 '2016-06-14',
 '2016-06-15',
 '2016-06-16',
 '2016-06-17',
 '2016-06-18',
 '2016-06-19',
 '2016-06-20',
 '2016-06-21',
 '2016-06-22',
 '2016-06-23',
 '2016-06-24',
 '2016-06-25',
 '2016-06-26',
 '2016-06-27',
 '2016-06-28',
 '2016-06-29',
 '2016-06-30',
 '2016-07-01',
 '2016-07-02',
 '2016-07-03',
 '2016-07-04',
 '2016-07-05',
 '2016-07-06',
 '2016-07-07',
 '2016-07-08',
 '2016-07-09',
 '2016-07-10',
 '2016-07-11',
 '2016-07-12',
 '2016-07-13',
 '2016-07-14',
 '2016-07-15',
 '2016-07-16',
 '2016-07-17',
 '2016-07-18',
 '2016-07-19',
 '2016-07-20',
 '2016-07-21',
 '2016-07-22',
 '2016-07-23',
 '2016-07-24',
 '2016-07-25',
 '2016-07-26',
 '2016-07-27',
 '2016-07-28',
 '2016-07-29',
 '2016-07-30',
 '2016-07-31',
 '2016-08-01',
 '2016-08-02',
 '2016-08-03',
 '2016-08-04',
 '2016-08-05',
 '2016-08-06',
 '2016-08-07',
 '2016-08-08',
 '2016-08-09',
 '2016-08-10',
 '2016-08-11',
 '2016-08-12',
 '2016-08-13',
 '2016-08-14',
 '2016-08-15',
 '2016-08-16',
 '2016-08-17',
 '2016-08-18',
 '2016-08-19',
 '2016-08-20',
 '2016-08-21',
 '2016-08-22',
 '2016-08-23',
 '2016-08-24',
 '2016-08-25',
 '2016-08-26',
 '2016-08-27',
 '2016-08-28',
 '2016-08-29',
 '2016-08-30',
 '2016-08-31',
 '2016-09-01',
 '2016-09-02',
 '2016-09-03',
 '2016-09-04',
 '2016-09-05',
 '2016-09-06',
 '2016-09-07',
 '2016-09-08',
 '2016-09-09',
 '2016-09-10',
 '2016-09-11',
 '2016-09-12',
 '2016-09-13',
 '2016-09-14',
 '2016-09-15',
 '2016-09-16',
 '2016-09-17',
 '2016-09-18',
 '2016-09-19',
 '2016-09-20',
 '2016-09-21',
 '2016-09-22',
 '2016-09-23',
 '2016-09-24',
 '2016-09-25',
 '2016-09-26',
 '2016-09-27',
 '2016-09-28',
 '2016-09-29',
 '2016-09-30',
 '2016-10-01',
 '2016-10-02',
 '2016-10-03',
 '2016-10-04',
 '2016-10-05',
 '2016-10-06',
 '2016-10-07',
 '2016-10-08',
 '2016-10-09',
 '2016-10-10',
 '2016-10-11',
 '2016-10-12',
 '2016-10-13',
 '2016-10-14',
 '2016-10-15',
 '2016-10-16',
 '2016-10-17',
 '2016-10-18',
 '2016-10-19',
 '2016-10-20',
 '2016-10-21',
 '2016-10-22',
 '2016-10-23',
 '2016-10-24',
 '2016-10-25',
 '2016-10-26',
 '2016-10-27',
 '2016-10-28',
 '2016-10-29',
 '2016-10-30',
 '2016-10-31',
 '2016-11-01',
 '2016-11-02',
 '2016-11-03',
 '2016-11-04',
 '2016-11-05',
 '2016-11-06',
 '2016-11-07',
 '2016-11-08',
 '2016-11-09',
 '2016-11-10',
 '2016-11-11',
 '2016-11-12',
 '2016-11-13',
 '2016-11-14',
 '2016-11-15',
 '2016-11-16',
 '2016-11-17',
 '2016-11-18',
 '2016-11-19',
 '2016-11-20',
 '2016-11-21',
 '2016-11-22',
 '2016-11-23',
 '2016-11-24',
 '2016-11-25',
 '2016-11-26',
 '2016-11-27',
 '2016-11-28',
 '2016-11-29',
 '2016-11-30',
 '2016-12-01',
 '2016-12-02',
 '2016-12-03',
 '2016-12-04',
 '2016-12-05',
 '2016-12-06',
 '2016-12-07',
 '2016-12-08',
 '2016-12-09',
 '2016-12-10',
 '2016-12-11',
 '2016-12-12',
 '2016-12-13',
 '2016-12-14',
 '2016-12-15',
 '2016-12-16',
 '2016-12-17',
 '2016-12-18',
 '2016-12-19',
 '2016-12-20',
 '2016-12-21',
 '2016-12-22',
 '2016-12-23',
 '2016-12-24',
 '2016-12-25',
 '2016-12-26',
 '2016-12-27',
 '2016-12-28',
 '2016-12-29',
 '2016-12-30',
 '2016-12-31',
 '2017-01-01',
 '2017-01-02',
 '2017-01-03',
 '2017-01-04',
 '2017-01-05',
 '2017-01-06',
 '2017-01-07',
 '2017-01-08',
 '2017-01-09',
 '2017-01-10',
 '2017-01-11',
 '2017-01-12',
 '2017-01-13',
 '2017-01-14',
 '2017-01-15',
 '2017-01-16',
 '2017-01-17',
 '2017-01-18',
 '2017-01-19',
 '2017-01-20',
 '2017-01-21',
 '2017-01-22',
 '2017-01-23',
 '2017-01-24',
 '2017-01-25',
 '2017-01-26',
 '2017-01-27',
 '2017-01-28',
 '2017-01-29',
 '2017-01-30',
 '2017-01-31',
 '2017-02-01',
 '2017-02-02',
 '2017-02-03',
 '2017-02-04',
 '2017-02-05',
 '2017-02-06',
 '2017-02-07',
 '2017-02-08',
 '2017-02-09',
 '2017-02-10',
 '2017-02-11',
 '2017-02-12',
 '2017-02-13',
 '2017-02-14',
 '2017-02-15',
 '2017-02-16',
 '2017-02-17',
 '2017-02-18',
 '2017-02-19',
 '2017-02-20',
 '2017-02-21',
 '2017-02-22',
 '2017-02-23',
 '2017-02-24',
 '2017-02-25',
 '2017-02-26',
 '2017-02-27',
 '2017-02-28',
 '2017-03-01',
 '2017-03-02',
 '2017-03-03',
 '2017-03-04',
 '2017-03-05',
 '2017-03-06',
 '2017-03-07',
 '2017-03-08',
 '2017-03-09',
 '2017-03-10',
 '2017-03-11',
 '2017-03-12',
 '2017-03-13',
 '2017-03-14',
 '2017-03-15',
 '2017-03-16',
 '2017-03-17',
 '2017-03-18',
 '2017-03-19',
 '2017-03-20',
 '2017-03-21',
 '2017-03-22',
 '2017-03-23',
 '2017-03-24',
 '2017-03-25',
 '2017-03-26',
 '2017-03-27',
 '2017-03-28',
 '2017-03-29',
 '2017-03-30',
 '2017-03-31',
 '2017-04-01',
 '2017-04-02',
 '2017-04-03',
 '2017-04-04',
 '2017-04-05',
 '2017-04-06',
 '2017-04-07',
 '2017-04-08',
 '2017-04-09',
 '2017-04-10',
 '2017-04-11',
 '2017-04-12',
 '2017-04-13',
 '2017-04-14',
 '2017-04-15',
 '2017-04-16',
 '2017-04-17',
 '2017-04-18',
 '2017-04-19',
 '2017-04-20',
 '2017-04-21',
 '2017-04-22',
 '2017-04-23',
 '2017-04-24',
 '2017-04-25',
 '2017-04-26',
 '2017-04-27',
 '2017-04-28',
 '2017-04-29',
 '2017-04-30',
 '2017-05-01',
 '2017-05-02',
 '2017-05-03',
 '2017-05-04',
 '2017-05-05',
 '2017-05-06',
 '2017-05-07',
 '2017-05-08',
 '2017-05-09',
 '2017-05-10',
 '2017-05-11',
 '2017-05-12',
 '2017-05-13',
 '2017-05-14',
 '2017-05-15',
 '2017-05-16',
 '2017-05-17',
 '2017-05-18',
 '2017-05-19',
 '2017-05-20',
 '2017-05-21',
 '2017-05-22',
 '2017-05-23',
 '2017-05-24',
 '2017-05-25',
 '2017-05-26',
 '2017-05-27',
 '2017-05-28',
 '2017-05-29',
 '2017-05-30',
 '2017-05-31',
 '2017-06-01',
 '2017-06-02',
 '2017-06-03',
 '2017-06-04',
 '2017-06-05',
 '2017-06-06',
 '2017-06-07',
 '2017-06-08',
 '2017-06-09',
 '2017-06-10',
 '2017-06-11',
 '2017-06-12',
 '2017-06-13',
 '2017-06-14',
 '2017-06-15',
 '2017-06-16',
 '2017-06-17',
 '2017-06-18',
 '2017-06-19',
 '2017-06-20',
 '2017-06-21',
 '2017-06-22',
 '2017-06-23',
 '2017-06-24',
 '2017-06-25',
 '2017-06-26',
 '2017-06-27',
 '2017-06-28',
 '2017-06-29',
 '2017-06-30',
 '2017-07-01',
 '2017-07-02',
 '2017-07-03',
 '2017-07-04',
 '2017-07-05',
 '2017-07-06',
 '2017-07-07',
 '2017-07-08',
 '2017-07-09',
 '2017-07-10',
 '2017-07-11',
 '2017-07-12',
 '2017-07-13',
 '2017-07-14',
 '2017-07-15',
 '2017-07-16',
 '2017-07-17',
 '2017-07-18',
 '2017-07-19',
 '2017-07-20',
 '2017-07-21',
 '2017-07-22',
 '2017-07-23',
 '2017-07-24',
 '2017-07-25',
 '2017-07-26',
 '2017-07-27',
 '2017-07-28',
 '2017-07-29',
 '2017-07-30',
 '2017-07-31',
 '2017-08-01',
 '2017-08-02',
 '2017-08-03',
 '2017-08-04',
 '2017-08-05',
 '2017-08-06',
 '2017-08-07',
 '2017-08-08',
 '2017-08-09',
 '2017-08-10',
 '2017-08-11',
 '2017-08-12',
 '2017-08-13',
 '2017-08-14',
 '2017-08-15']

In [2]:
len(dates)

958

In [5]:
np.datetime64('2015-01-01') - np.datetime64('2013-01-01')

numpy.timedelta64(730,'D')

In [7]:
df_train = feather.read_dataframe('../cache/train10_t.feather')

In [9]:
df_train.shape

(125497040, 26)

In [8]:
df_train[df_train.store_nbr == 20]

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,family,class,perishable,city,...,mon,dow,doy,dcount,type,description,pd,wbe,wae,wfe
41089466,41089466,2015-02-13,20,103501,7.00,False,CLEANING,3008,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089467,41089467,2015-02-13,20,105576,56.00,False,GROCERY I,1045,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089468,41089468,2015-02-13,20,105693,5.00,False,GROCERY I,1034,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089469,41089469,2015-02-13,20,106716,22.00,False,GROCERY I,1032,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089470,41089470,2015-02-13,20,108079,1.00,False,GROCERY I,1030,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089471,41089471,2015-02-13,20,108696,9.00,False,DELI,2636,1,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089472,41089472,2015-02-13,20,108698,2.00,False,DELI,2644,1,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089473,41089473,2015-02-13,20,108701,12.00,False,DELI,2644,1,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089474,41089474,2015-02-13,20,108786,61.00,False,CLEANING,3044,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089475,41089475,2015-02-13,20,108797,8.00,False,GROCERY I,1004,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089476,41089476,2015-02-13,20,108831,6.56,False,POULTRY,2416,1,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089477,41089477,2015-02-13,20,108833,3.00,False,EGGS,2502,1,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089478,41089478,2015-02-13,20,108952,13.00,False,CLEANING,3024,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089479,41089479,2015-02-13,20,111223,53.00,False,GROCERY I,1034,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089480,41089480,2015-02-13,20,111397,19.00,False,GROCERY I,1072,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089481,41089481,2015-02-13,20,112830,7.00,False,GROCERY I,1044,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089482,41089482,2015-02-13,20,114778,4.00,False,GROCERY I,1016,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089483,41089483,2015-02-13,20,114790,23.00,False,GROCERY I,1004,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089484,41089484,2015-02-13,20,114799,57.00,False,PERSONAL CARE,4126,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089485,41089485,2015-02-13,20,115267,19.00,False,CLEANING,3034,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089486,41089486,2015-02-13,20,115611,38.00,False,GROCERY I,1014,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089487,41089487,2015-02-13,20,115720,16.00,False,GROCERY I,1084,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089488,41089488,2015-02-13,20,115850,41.00,False,GROCERY I,1004,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089489,41089489,2015-02-13,20,115891,5.00,False,GROCERY I,1016,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089490,41089490,2015-02-13,20,115892,5.00,False,GROCERY I,1016,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089491,41089491,2015-02-13,20,115893,9.00,False,GROCERY I,1016,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089492,41089492,2015-02-13,20,115894,26.00,False,GROCERY I,1016,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089493,41089493,2015-02-13,20,116017,49.00,False,GROCERY I,1072,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089494,41089494,2015-02-13,20,116018,2.00,False,GROCERY I,1072,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
41089495,41089495,2015-02-13,20,116279,5.00,False,GROCERY I,1056,0,Quito,...,2,4,44,735642,Work Day,Normal,0,62,0,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125431427,125431427,2017-08-15,20,2081064,12.00,False,PREPARED FOODS,2966,1,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431428,125431428,2017-08-15,20,2081095,4.00,False,PREPARED FOODS,2962,1,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431429,125431429,2017-08-15,20,2081139,7.00,False,PREPARED FOODS,2986,1,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431430,125431430,2017-08-15,20,2081161,17.00,False,PREPARED FOODS,2966,1,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431431,125431431,2017-08-15,20,2083837,10.00,True,BEVERAGES,1118,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431432,125431432,2017-08-15,20,2083859,19.00,True,BEVERAGES,1118,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431433,125431433,2017-08-15,20,2084557,10.00,False,CLEANING,3040,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431434,125431434,2017-08-15,20,2087374,5.00,False,DAIRY,2162,1,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431435,125431435,2017-08-15,20,2087409,12.00,True,BEVERAGES,1132,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431436,125431436,2017-08-15,20,2087543,7.00,False,DAIRY,2162,1,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431437,125431437,2017-08-15,20,2087567,5.00,False,DAIRY,2162,1,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431438,125431438,2017-08-15,20,2087978,5.00,False,BEVERAGES,1114,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431439,125431439,2017-08-15,20,2088922,15.00,False,GROCERY I,1076,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431440,125431440,2017-08-15,20,2089339,8.00,False,GROCERY I,1006,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431441,125431441,2017-08-15,20,2099230,2.00,False,BEAUTY,4252,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431442,125431442,2017-08-15,20,2101795,1.00,True,BEAUTY,4222,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431443,125431443,2017-08-15,20,2105347,1.00,False,BEAUTY,4254,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431444,125431444,2017-08-15,20,2106464,2.00,True,BEVERAGES,1148,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431445,125431445,2017-08-15,20,2108569,1.00,False,GROCERY I,1086,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431446,125431446,2017-08-15,20,2109909,1.00,False,GROCERY I,1074,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431447,125431447,2017-08-15,20,2110456,10.00,False,BEVERAGES,1120,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431448,125431448,2017-08-15,20,2111684,1.00,False,BEVERAGES,1120,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431449,125431449,2017-08-15,20,2112404,4.00,True,DAIRY,2108,1,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431450,125431450,2017-08-15,20,2113343,3.00,False,BEVERAGES,1114,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431451,125431451,2017-08-15,20,2113914,12.00,True,CLEANING,3040,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431452,125431452,2017-08-15,20,2116416,7.00,False,GROCERY I,1060,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431453,125431453,2017-08-15,20,2122188,5.00,False,GROCERY I,1084,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431454,125431454,2017-08-15,20,2123410,1.00,False,GROCERY I,1012,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431455,125431455,2017-08-15,20,2123468,1.00,False,GROCERY I,1068,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70
125431456,125431456,2017-08-15,20,2123839,1.00,False,BEVERAGES,1122,0,Quito,...,8,1,227,736556,Work Day,Normal,1,0,70,70

In [10]:
df_train[df_train.store_nbr == 20].shape

(1665985, 26)

In [2]:
df12 = pd.DataFrame({'group_ids':[1,1,1,2,2,2],'dates':['2016-04-01','2016-04-20','2016-04-28','2016-04-05','2016-04-20','2016-04-29'],'event_today_in_group':[0,1,0,1,1,0]})

In [46]:
df12

        dates  event_today_in_group  group_ids
0  2016-04-01                     0          1
1  2016-04-20                     1          1
2  2016-04-28                     0          1
3  2016-04-05                     1          2
4  2016-04-20                     1          2
5  2016-04-29                     0          2

In [47]:
df = df12

In [48]:
df['dates'] = df['dates'].apply(lambda x: np.datetime64(x))

In [49]:
df.groupby('group_ids')['dates'].diff()

0       NaT
1   19 days
2    8 days
3       NaT
4   15 days
5    9 days
Name: dates, dtype: timedelta64[ns]

In [50]:
def get_days(x):
    try:
        return x.days
    except:
        return 0

In [51]:
df['days_since_last_event'] = df.groupby('group_ids')['dates'].diff().map(lambda x: get_days(x))

In [52]:
df

       dates  event_today_in_group  group_ids  days_since_last_event
0 2016-04-01                     0          1                      0
1 2016-04-20                     1          1                     19
2 2016-04-28                     0          1                      8
3 2016-04-05                     1          2                      0
4 2016-04-20                     1          2                     15
5 2016-04-29                     0          2                      9

In [41]:
df['days_from_next_event'] = df.groupby('group_ids')['dates'].diff().map(lambda x: get_days(x))

In [42]:
df.loc[:, 'days_from_next_event'] = df.groupby(['group_ids', df['event_today_in_group'].shift(-1).cumsum()])['days_from_next_event'].cumsum()

In [43]:
df.loc[:, 'days_since_last_event'] = df.groupby(['group_ids', df['event_today_in_group'].shift().cumsum()])['days_since_last_event'].cumsum()

In [44]:
df

,dates,event_today_in_group,group_ids,days_since_last_event,days_from_next_event
0,2016-04-01,0,1,-1,0
1,2016-04-20,1,1,19,19
2,2016-04-28,0,1,8,8
3,2016-04-05,1,2,0,0
4,2016-04-20,1,2,15,15
5,2016-04-29,0,2,9,-1

In [54]:
a = [True, False, True]

In [56]:
np.where(a)

(array([0, 2]),)

In [57]:
b = [1, 0, 1]

In [58]:
np.where(b)

(array([0, 2]),)

In [29]:
df12 = pd.DataFrame({'group_ids':[1,1,1,2,2,2],'dates':['2016-04-01','2016-04-20','2016-04-28','2016-04-05','2016-04-20','2016-04-29'],'event_today_in_group':[0,1,0,1,1,0]})

In [60]:
df12

        dates  event_today_in_group  group_ids
0  2016-04-01                     0          1
1  2016-04-20                     1          1
2  2016-04-28                     0          1
3  2016-04-05                     1          2
4  2016-04-20                     1          2
5  2016-04-29                     0          2

In [76]:
l = list(np.transpose(*np.where(df12.event_today_in_group)))

In [77]:
l

[1, 3, 4]

In [78]:
for i in l:
    print(i)

1
3
4

In [30]:
df12

        dates  event_today_in_group  group_ids
0  2016-04-01                     0          1
1  2016-04-20                     1          1
2  2016-04-28                     0          1
3  2016-04-05                     1          2
4  2016-04-20                     1          2
5  2016-04-29                     0          2

In [27]:
df12.loc[0, 'test'] = int(1)

In [28]:
df12

        dates  event_today_in_group  group_ids  test
0  2016-04-01                     0          1   1.0
1  2016-04-20                     1          1   0.0
2  2016-04-28                     0          1   NaN
3  2016-04-05                     1          2   NaN
4  2016-04-20                     1          2   NaN
5  2016-04-29                     0          2   NaN

In [31]:
df12.sort('dates')

/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

        dates  event_today_in_group  group_ids
0  2016-04-01                     0          1
3  2016-04-05                     1          2
1  2016-04-20                     1          1
4  2016-04-20                     1          2
2  2016-04-28                     0          1
5  2016-04-29                     0          2